

import React, { useState, useRef } from 'react';
import { Wine, PurchaseAnalysis } from '../types';
import { analyzePurchase } from '../services/geminiService';
import { CameraIcon, LogoutIcon, ShopIcon, WineIcon, ExternalLinkIcon, ChefIcon } from '../components/Icons';
import PriceComparison from '../components/PriceComparison'; // New

interface ShopViewProps {
  inventory: Wine[];
  onLogout: () => void;
  onAddToInventory: (wine: Wine) => void;
  onAiUsed: () => void;
  isPremium: boolean; // New Prop
}

const ShopView: React.FC<ShopViewProps> = ({ inventory, onLogout, onAddToInventory, onAiUsed, isPremium }) => {
  const [mode, setMode] = useState<'camera' | 'link'>('camera');
  const [image, setImage] = useState<string | null>(null);
  const [linkUrl, setLinkUrl] = useState('');
  const [price, setPrice] = useState<number | ''>('');
  const [loading, setLoading] = useState(false);
  const [analysis, setAnalysis] = useState<PurchaseAnalysis | null>(null);
  const fileInputRef = useRef<HTMLInputElement>(null);

  const handleFileChange = (e: React.ChangeEvent<HTMLInputElement>) => {
      const file = e.target.files?.[0];
      if (file) {
          const reader = new FileReader();
          reader.onloadend = () => setImage(reader.result as string);
          reader.readAsDataURL(file);
      }
  };

  const handleAnalyze = async (e: React.FormEvent) => {
      e.preventDefault();
      
      if (mode === 'camera' && !image) return;
      if (mode === 'link' && !linkUrl) return;
      if (!price) {
          alert("Inserisci il prezzo per valutare l'offerta.");
          return;
      }

      const inputPrice = Number(price);
      
      setLoading(true);
      setAnalysis(null);
      try {
          const input = mode === 'camera' 
            ? { type: 'image' as const, data: image! }
            : { type: 'url' as const, data: linkUrl };

          const result = await analyzePurchase(input, inputPrice, inventory);
          setAnalysis(result);
          onAiUsed(); // Track
          
      } catch (error: any) {
          alert(`Errore analisi: ${error.message || "Riprova più tardi."}`);
          console.error(error);
      } finally {
          setLoading(false);
      }
  };

  const handleBuy = () => {
      if (!analysis) return;
      const today = new Date().toISOString().split('T')[0];
      
      const newWine: Wine = {
          id: '', // Will be generated by App
          name: analysis.wineDetails.name || 'Nuovo Acquisto',
          producer: analysis.wineDetails.producer || 'Sconosciuto',
          year: analysis.wineDetails.year || 'N/A',
          type: analysis.wineDetails.type as any,
          region: analysis.wineDetails.region || '',
          grape: analysis.wineDetails.grape || '',
          alcohol: analysis.wineDetails.alcohol || '',
          purchaseDate: today,
          price: Number(price) || analysis.marketPriceEstimate || 0,
          quantity: 1,
          location: 'Da posizionare',
          storageTemp: '12-16°C',
          storageAdvice: 'Da verificare',
          servingTemp: '16-18°C',
          servingAdvice: 'Aprire prima',
          foodPairings: analysis.wineDetails.foodPairings || [],
          imageUrl: image || undefined,
          drinkWindow: `${new Date().getFullYear()}-${new Date().getFullYear() + 3}`,
          marketPrice: analysis.marketPriceEstimate || Number(price)
      };
      
      onAddToInventory(newWine);
      alert("Vino aggiunto alla cantina!");
      // Reset
      setImage(null);
      setLinkUrl('');
      setPrice('');
      setAnalysis(null);
  };

  const getDealColor = (rating: string) => {
      switch(rating) {
          case 'Excellent': return 'bg-green-100 text-green-800 border-green-200';
          case 'Good': return 'bg-blue-50 text-blue-800 border-blue-200';
          case 'Fair': return 'bg-yellow-50 text-yellow-800 border-yellow-200';
          default: return 'bg-red-50 text-red-800 border-red-200';
      }
  };

  return (
    <div className="h-full flex flex-col bg-stone-50 overflow-hidden">
      {/* Header */}
      <div className="bg-white border-b border-gray-200 p-6 shadow-sm z-10 flex justify-between items-start">
        <div>
            <h1 className="text-2xl font-serif font-bold text-gray-900 flex items-center gap-2">
                <ShopIcon className="w-8 h-8 text-wine-600" filled />
                Shop Advisor
            </h1>
            <p className="text-sm text-gray-500 mt-1">
                Scansiona prima di comprare. Analisi prezzo e cantina.
            </p>
        </div>
        <button onClick={onLogout} className="text-gray-400 hover:text-wine-700 p-2">
            <LogoutIcon className="w-6 h-6" />
        </button>
      </div>

      <div className="flex-1 overflow-y-auto p-4 pb-24">
        
        {/* Input Section */}
        {!analysis && (
            <div className="space-y-6">
                
                {/* Mode Toggles */}
                <div className="flex p-1 bg-gray-200 rounded-xl">
                    <button 
                        onClick={() => setMode('camera')}
                        className={`flex-1 py-2 text-sm font-bold rounded-lg transition-all flex items-center justify-center gap-2 ${mode === 'camera' ? 'bg-white shadow-sm text-wine-700' : 'text-gray-500 hover:text-gray-700'}`}
                    >
                        <CameraIcon className="w-4 h-4" />
                        Foto
                    </button>
                    <button 
                        onClick={() => setMode('link')}
                        className={`flex-1 py-2 text-sm font-bold rounded-lg transition-all flex items-center justify-center gap-2 ${mode === 'link' ? 'bg-white shadow-sm text-wine-700' : 'text-gray-500 hover:text-gray-700'}`}
                    >
                        <ExternalLinkIcon className="w-4 h-4" />
                        Link
                    </button>
                </div>

                {mode === 'camera' ? (
                    <div 
                        onClick={() => fileInputRef.current?.click()}
                        className={`border-2 border-dashed rounded-2xl p-8 flex flex-col items-center justify-center transition-all cursor-pointer ${
                            image ? 'border-wine-500 bg-wine-50' : 'border-gray-300 hover:bg-gray-50'
                        }`}
                    >
                        {image ? (
                            <img src={image} alt="Preview" className="h-48 object-contain rounded shadow-sm" />
                        ) : (
                            <>
                                <div className="bg-wine-100 p-4 rounded-full mb-3">
                                    <CameraIcon className="w-8 h-8 text-wine-600" />
                                </div>
                                <span className="font-medium text-gray-600">Tocca per scattare foto</span>
                            </>
                        )}
                        <input 
                            type="file" 
                            ref={fileInputRef} 
                            className="hidden" 
                            accept="image/*"
                            capture="environment" 
                            onChange={handleFileChange} 
                        />
                    </div>
                ) : (
                    <div className="bg-white p-4 rounded-xl shadow-sm border border-gray-200">
                        <label className="block text-sm font-bold text-gray-700 mb-2">Link E-commerce</label>
                        <input 
                            type="url" 
                            value={linkUrl}
                            onChange={(e) => setLinkUrl(e.target.value)}
                            className="w-full p-3 border border-gray-300 rounded-xl focus:ring-2 focus:ring-wine-600 outline-none"
                            placeholder="https://www.tannico.it/..."
                        />
                        <p className="text-xs text-gray-500 mt-2">Incolla l'URL della pagina prodotto.</p>
                    </div>
                )}

                <div className="bg-white p-4 rounded-xl shadow-sm border border-gray-200">
                    <label className="block text-sm font-bold text-gray-700 mb-2">
                        Prezzo Offerta (€) <span className="text-red-500">*</span>
                    </label>
                    <input 
                        type="number" 
                        required
                        value={price}
                        onChange={(e) => setPrice(Number(e.target.value))}
                        className="w-full p-3 text-lg border border-gray-300 rounded-xl focus:ring-2 focus:ring-wine-600 outline-none"
                        placeholder="Es. 25.00"
                    />
                </div>

                <button 
                    onClick={handleAnalyze}
                    disabled={(mode === 'camera' && !image) || (mode === 'link' && !linkUrl) || !price || loading}
                    className="w-full py-4 bg-wine-700 text-white font-bold rounded-xl shadow-lg hover:bg-wine-800 disabled:opacity-50 disabled:cursor-not-allowed transition-all"
                >
                    {loading ? 'Analisi in corso...' : 'Analizza Acquisto'}
                </button>
            </div>
        )}

        {/* Results Section */}
        {analysis && (
            <div className="space-y-4 animate-in slide-in-from-bottom duration-500">
                {/* Wine Header */}
                <div className="bg-white p-5 rounded-xl shadow-sm border border-gray-100">
                    <div className="flex justify-between items-start">
                        <div>
                            <span className="text-xs font-bold text-gray-400 uppercase">{analysis.wineDetails.type}</span>
                            <h2 className="text-2xl font-serif font-bold text-gray-900 leading-tight">{analysis.wineDetails.name}</h2>
                            <p className="text-gray-600">{analysis.wineDetails.producer} • {analysis.wineDetails.year}</p>
                        </div>
                        <div className="bg-gray-900 text-white px-3 py-1 rounded-lg text-center">
                            <span className="block text-xs text-gray-400 uppercase">Qualità</span>
                            <span className="font-bold text-xl">{analysis.qualityScore}/100</span>
                        </div>
                    </div>
                    <p className="mt-3 text-sm text-gray-600 italic border-l-2 border-wine-300 pl-3">
                        "{analysis.sommelierNotes}"
                    </p>

                    {/* Food Pairings Display */}
                    {analysis.wineDetails.foodPairings && analysis.wineDetails.foodPairings.length > 0 && (
                        <div className="mt-4 pt-4 border-t border-gray-100">
                            <h4 className="text-xs font-bold text-gray-500 uppercase mb-2 flex items-center gap-1">
                                <ChefIcon className="w-3 h-3" /> Abbinamenti
                            </h4>
                            <div className="flex flex-wrap gap-2">
                                {analysis.wineDetails.foodPairings.map((pair, idx) => (
                                    <span key={idx} className="text-xs bg-orange-50 text-orange-700 px-2 py-1 rounded-lg border border-orange-100 font-medium">
                                        {pair}
                                    </span>
                                ))}
                            </div>
                        </div>
                    )}
                </div>

                {/* Price Analysis & Comparison */}
                <div className={`p-5 rounded-xl border ${getDealColor(analysis.dealRating)}`}>
                    <div className="flex justify-between items-center mb-2">
                        <h3 className="font-bold uppercase tracking-wide text-sm flex items-center gap-2">
                            Analisi Prezzo
                            <span className="bg-white/50 px-2 py-0.5 rounded text-xs border border-black/10">
                                {analysis.dealRating} Deal
                            </span>
                        </h3>
                    </div>
                    <div className="flex justify-between items-end mb-4">
                        <div>
                             <p className="text-xs opacity-70 mb-1">Prezzo Offerta</p>
                             <p className="text-2xl font-bold">€{Number(price).toFixed(2)}</p>
                        </div>
                        <div className="text-right">
                             <p className="text-xs opacity-70 mb-1">Stima Mercato</p>
                             <p className="text-xl font-semibold opacity-90">~€{analysis.marketPriceEstimate.toFixed(2)}</p>
                        </div>
                    </div>
                    
                    {/* NEW: Verify prices button integrated directly in the result card */}
                    <div className="bg-white/50 rounded-xl p-2">
                        <PriceComparison 
                            name={analysis.wineDetails.name || ''} 
                            producer={analysis.wineDetails.producer || ''} 
                            year={analysis.wineDetails.year || ''}
                            isPremium={isPremium} // Pass prop
                        />
                    </div>
                </div>

                {/* Cellar Fit Analysis - The Killer Feature */}
                <div className="bg-gradient-to-br from-indigo-50 to-purple-50 p-5 rounded-xl border border-indigo-100">
                    <h3 className="font-bold text-indigo-900 flex items-center gap-2">
                        <WineIcon className="w-5 h-5" filled />
                        Integrazione Cantina
                    </h3>
                    <div className={`inline-block px-3 py-1 rounded-full text-xs font-bold mb-2 ${
                        analysis.cellarFit.isRecommended ? 'bg-indigo-600 text-white' : 'bg-gray-200 text-gray-600'
                    }`}>
                        {analysis.cellarFit.isRecommended ? 'Consigliato' : 'Valuta bene'}
                    </div>
                    <p className="text-sm text-indigo-800 leading-relaxed">
                        {analysis.cellarFit.reasoning}
                    </p>
                </div>

                <div className="flex gap-3 pt-2">
                    <button 
                        onClick={() => { setAnalysis(null); setImage(null); setLinkUrl(''); setPrice(''); }}
                        className="flex-1 py-3 text-gray-600 bg-white border border-gray-200 hover:bg-gray-50 rounded-xl font-medium"
                    >
                        Nuova Analisi
                    </button>
                    <button 
                        onClick={handleBuy}
                        className="flex-1 py-3 bg-wine-700 text-white hover:bg-wine-800 rounded-xl font-bold shadow-lg shadow-wine-200"
                    >
                        Compra e Aggiungi
                    </button>
                </div>
            </div>
        )}

      </div>
    </div>
  ); 
};

export default ShopView;
